version: '3.1'

services:

  consignment-cli:
    build: ./consignment-cli
    environment:
      MICRO_REGISTRY: "mdns"
    depends_on:
      - consignment-service
    links:
      - consignment-service
    restart: always

  consignment-service:
    build: ./consignment-service
    ports:
      - 50051:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "datastore:27017"
    depends_on:
      - vessel-service
      - datastore

  vessel-service:
    build: ./vessel-service
    ports:
    - 50052:50051
    environment:
      MICRO_ADRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "datastore:27017"
    depends_on:
    - datastore

  datastore:
    image: mongo:4.0.4
    ports:
      - 27017:27017
#    volumes:
#    - /usr/local/var/mongodb:/data/db
